[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  HUGO_VERSION = "0.64.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "npm run build && npm run ipfs-deploy"

[[redirects]]
  from = "https://bubai.netlify.com/*"
  to = "https://bubais.top/:splat"
  force = true
